roles:
  - name: geerlingguy.docker_arm
    version: 5.0.0
  - name: christiangda.awscli
    version: 1.0.2
  - name: christiangda.awscli_configure
    version: 0.0.5
  - name: diodonfrost.terraform
    version: 1.6.1