---
- name:
  hosts:  all
  become: true
  vars:
  docker_users:
    - panda
    - vagrant 
  roles: 
    - user
    - packages
    - geerlingguy.docker_arm
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform